[project]
name = "deepshape2"
version = "0.1.0"
description = "Wide field radio shape measurements with deep learning"
readme = "README.md"
requires-python = "==3.12"

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"
